controller_list:
  - name: fake_arms_controller
    type: $(arg fake_execution_type)
    joints:
      - base_link_to_rotator1
      - pivot1_to_arm1
      - arm1_to_pivot1b
      - pivot1b_to_arm1b
      - arm1b_to_pivot2
      - pivot2_to_arm2
initial:  # Define initial robot poses per group
  - group: arms
    pose: default